### ISSUE TITLE
Some issues in Observer.php and htmlentities for PHP => 5.4

### ISSUE THREAD

**Issue by zuiko** [gaiterjones/magento-GetCustomerFeedback#1]
Hello GaiterJones, some years after...

if someone have problems with special characters in customer name, or product name, be sure your server does not change its PHP version. The issue is around htmlentities  in /app/code/local/PAJ/GetCustomerFeedback/Model/Observer.php.
In fact if PHP is < 5.4 htmlentities treats the string per default as ISO-8859-1 encoded.
if PHP => 5.4 htmlentities treats the string per default as utf-8 encoded.

in Observer.php you can read :
`$cartProductName=utf8_decode($cartProduct->getName());`
After that $cartProductName contains a string ISO-8859-1 encoded.

Some lines after you can read the preparation of the email content with product name :
`$cartHTML=$cartHTML. '<td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">'. htmlentities($cartProductName). '</td>'. $newline;`

If you have special characters in $cartProductName , htmlentities($cartProductName) returns nothing because an utf-8 encoding is waited.
For me the best solution is to change the 1st line in :
`$cartProductName=$cartProduct->getName();`
and code the 2nd with:
htmlentities($cartProductName, ENT_QUOTES, "UTF-8")
adding arguments to htmlentities to manage surely its behaviour for all languages.

You have to add also htmlentities around $customerName on this line:
`$greeting = '<tr><td valign="top"><h1 style="font-size:22px; font-weight:normal; line-height:22px; margin:0 0 11px 0;"">'. $this->getTranslation('Hello',$storeID). ' '. $customerName. ',</h1>';`
but do that like this to be sure:
htmlentities($customerName, ENT_QUOTES, "UTF-8")

and modify these 2 lines in the same logic (utf8_decode not useful):

```
        $customerFirstName = strtolower(utf8_decode(Mage::getSingleton('customer/session')->getCustomer()->getFirstname()));
        $customerLastName = strtolower(utf8_decode(Mage::getSingleton('cus



tomer/session')->getCustomer()->getLastname()));
```

as this:

```
$customerFirstName = strtolower(Mage::getSingleton('customer/session')->getCustomer()->getFirstname());
$customerLastName = strtolower(Mage::getSingleton('customer/session')->getCustomer()->getLastname());
```

With these updates, this extension works perfectly now in french under a 5.5.37 PHP version server.
See attached, my new version for Observer.php into zip including this update (but I don't know if github will accept it).
Zuiko

**Comment by zuiko** [comment]
Just a precision: 
htmlentities($cartProductName, ENT_QUOTES, "UTF-8")
this coding insures that it will work for every PHP versions >= 4.1.0

**Comment by gaiterjones** [comment]
Thanks for your help with this.
